# Site settings
title: Your Website's Title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write a short description about your website here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima # replace 'minima' with your preferred theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional settings
author: Your Name
twitter_username: yourusername
github_username:  yourgithub

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
